package org.hibernate;
// Generated Oct 1, 2018, 4:07:21 PM by Hibernate Tools 5.3.1.Final
import javax.persistence.*;
/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="Employee")
public class Employee implements java.io.Serializable {
	
	@Id
	private EmployeeId id;

	public Employee() {
	}

	public Employee(EmployeeId id) {
		this.id = id;
	}

	public EmployeeId getId() {
		return this.id;
	}

	public void setId(EmployeeId id) {
		this.id = id;
	}

}
